### ISSUE TITLE
Blogpost Consent and Preferred Handle

### ISSUE THREAD

**Issue by eisenjulian** [n-waves/multifit#52]
As we approach the time to publish a blogpost to share the results, we are looking for consent from the contributors to be named in it. Also please add your personal page or twitter handle or the preferred URL where clicking on your name should link to. Thank you all!

- [x] @aayux
- [x] @ademyanchuk 
- [x] @benjaminvdb 
- [x] @cahya-wirawan 
- [ ] @cstorm125 
- [x] @NirantK 
- [x] @tpietruszka

**Comment by NirantK** [comment]
https://twitter.com/NirantK

**Comment by eisenjulian** [comment]
How about the rest? @aayux @ademyanchuk @benjaminvdb @cahya-wirawan @cstorm125 @tpietruszka

**Comment by benjaminvdb** [comment]
Thanks for getting in touch @eisenjulian 👍 You can link to my [GitHub page](https://github.com/benjaminvdb).

I'm looking forward to reading the blog post 😄

**Comment by ademyanchuk** [comment]
Sure! My twitter handler is aDemyan4uk
Also, would love to read a blog post :)

**Comment by aayux** [comment]
That's odd, I thought I had checked my name. 

Anyhow, thanks for getting in touch! I look forward to the blog post. You can link my website: https://aayux.github.io

**Comment by tpietruszka** [comment]
Sure, thanks! My github page is fine ( https://github.com/tpietruszka )

**Comment by cahya-wirawan** [comment]
Thanks also for getting in touch. Here is my link: https://github.com/cahya-wirawan
By the way, what is the blog about?

**Comment by eisenjulian** [comment]
The blogpost explains in more detail the paper https://arxiv.org/abs/1909.04761

**Comment by cahya-wirawan** [comment]
Ok, thanks, I will read it.

**Comment by eisenjulian** [comment]
Awesome, we are only missing @cstorm125 now
