### ISSUE TITLE
Train on my own data

### ISSUE THREAD

**Issue by wonderfultina** [n-waves/multifit#59]
Hi,
 I want to ask a question,how can i train my own data ?
Thanks.

**Comment by sebastianruder** [comment]
Hi Catherine, we're just in the process of merging an example that shows how to do this. In the meantime, you can have a look at PR https://github.com/n-waves/multifit/pull/57

**Comment by eisenjulian** [comment]
Closing this at the moment. The examples in the notebooks folder are good starting points, the data is located as a train.csv and a test.csv file in the same folder.
