### ISSUE TITLE
Where can I find the dataset de.train.csv?

### ISSUE THREAD

**Issue by cahya-wirawan** [n-waves/multifit#68]
I am trying to run the notebook CLS-DE.ipynb, but I don't know where I can find the dataset. When I run following line in the notebook:

cls_dataset.load_clas_databunch(bs=exp.finetune_lm.bs).show_batch()

I got this error message:

FileNotFoundError: [Errno 2] File data/cls/de-music/de.train.csv does not exist: 'data/cls/de-music/de.train.csv'

**Comment by eisenjulian** [comment]
Hi, you can run the [`prepare_cls.py`](https://github.com/n-waves/multifit/blob/master/prepare_cls.py) script, pointing to the url at https://storage.googleapis.com/ulmfit/cls-full

**Comment by cahya-wirawan** [comment]
Thanks for the fast answer. I must have overlooked the info how to get the dataset

**Comment by Jiejiang1996** [comment]
> Hi, you can run the [`prepare_cls.py`](https://github.com/n-waves/multifit/blob/master/prepare_cls.py) script, pointing to the url at https://storage.googleapis.com/ulmfit/cls-full

Hi, when I run this prepare_cls.py script, it shows ERROR: The function received no value for the required argument: url_prefix. And there is nothing in this URL https://storage.googleapis.com/ulmfit/cls-full. What is the reason going to be?
